#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "chttp2/byte_buffer.hpp"
#include "chttp2/client_config.hpp"
#include "chttp2/flow.hpp"
#include "chttp2/frame.hpp"
#include "chttp2/frame_codec.hpp"
#include "chttp2/hpack/hpack.hpp"
#include "chttp2/http2_constants.hpp"
#include "chttp2/log.hpp"
#include "chttp2/protocol_event.hpp"
#include "chttp2/request.hpp"
#include "chttp2/stream.hpp"

namespace chttp2 {

struct ProtocolStepResult {
  std::vector<ByteBuffer> outbound;
  std::vector<ProtocolEvent> events;
  bool hasSubmittedStream{false};
  StreamId submittedStreamId{};
};

class Http2Protocol {
 public:
  Http2Protocol();
  explicit Http2Protocol(const ClientConfig& config);
  ~Http2Protocol();

  Http2Protocol(const Http2Protocol&) = delete;
  Http2Protocol& operator=(const Http2Protocol&) = delete;

  // Bootstraps the local HTTP/2 connection state and emits the client preface
  // plus the initial SETTINGS frame.
  ProtocolStepResult start();

  // Encodes a new request into one client-initiated stream and emits the
  // outbound frames generated by this state transition.
  ProtocolStepResult submitRequest(const Request& request);

  // Feeds raw bytes received from the transport into the protocol state
  // machine. The returned result contains both outbound frames and protocol
  // events generated while processing the input.
  ProtocolStepResult receiveBytes(const std::uint8_t* data, std::size_t len);

  // Aborts one stream from the local side and emits the required protocol
  // frames/events for that state transition.
  ProtocolStepResult cancelStream(StreamId streamId, ErrorCode errorCode);

  // Emits a PING frame for keepalive probing.
  ProtocolStepResult sendPing();

  // Initiates a local close of the protocol connection.
  ProtocolStepResult close();

  // Informs the protocol that the underlying transport has already closed.
  ProtocolStepResult onTransportClosed();

  void reset();

  bool isStarted() const { return started; }
  bool isClosed() const { return closed; }
  bool canSubmitRequests() const { return started && !closed && !sentGoaway && !receivedGoaway; }
  StreamId nextLocalStreamId() const { return nextStreamId; }
  std::size_t activeStreamCount() const { return streams.size(); }
  ErrorCode lastConnectionError() const { return connectionErrorCode; }
  const std::string& lastConnectionDebugData() const { return connectionDebugData; }

  // Peer settings (applied values).
  std::uint32_t peerMaxConcurrentStreams() const { return maxConcurrentStreams; }
  std::uint32_t peerMaxFrameSize() const { return maxFrameSize; }
  std::uint32_t peerInitialWindowSize() const { return initialWindowSize; }
  std::uint32_t peerMaxHeaderListSize() const { return maxHeaderListSize; }

 private:
  ProtocolStepResult receiveFrame(const RawFrame& frame);

  ProtocolStepResult processDataFrame(const RawFrame& frame);
  ProtocolStepResult processHeadersFrame(const RawFrame& frame);
  ProtocolStepResult processPriorityFrame(const RawFrame& frame);
  ProtocolStepResult processRstStreamFrame(const RawFrame& frame);
  ProtocolStepResult processSettingFrame(const RawFrame& frame);
  ProtocolStepResult processPushPromiseFrame(const RawFrame& frame);
  ProtocolStepResult processPingFrame(const RawFrame& frame);
  ProtocolStepResult processGoAwayFrame(const RawFrame& frame);
  ProtocolStepResult processWindowUpdateFrame(const RawFrame& frame);
  ProtocolStepResult processContinuationFrame(const RawFrame& frame);

  ProtocolStepResult failConnection(ErrorCode errorCode, const std::string& debugData);
  ProtocolStepResult failStream(StreamId streamId, ErrorCode errorCode, bool sendRst = false);
  void failAllStreams(ErrorCode errorCode, ProtocolStepResult& result);

  ProtocolStepResult processDataOnUnknownStream(const DataFrame& dataFrame);
  ProtocolStepResult handleHeaderBlockError(StreamId streamId, ErrorCode errorCode);

  void emitRequestHeaders(Stream* stream, ByteBuffer encoded, ProtocolStepResult* result);
  void emitPendingRequestBody(Stream* stream, ProtocolStepResult* result);
  ErrorCode decodeResponseHeaders(Stream* stream, bool endStream, ProtocolStepResult* result);
  ErrorCode validateResponseHeaderBlock(Stream* stream,
                                        const std::vector<HeaderField>& headers,
                                        bool endStream,
                                        bool* informationalHeaders) const;
  void finalizeRemoteStream(Stream* stream, ProtocolStepResult* result);

  ErrorCode applyPeerSettings(const SettingFrame& frame);
  SettingFrame buildLocalSettingsFrame() const;
  GoAwayFrame buildGoAwayFrame(ErrorCode errorCode, const std::string& debugData) const;
  RstStreamFrame buildRstStreamFrame(StreamId streamId, ErrorCode errorCode) const;
  WindowUpdateFrame buildWindowUpdateFrame(StreamId streamId, std::uint32_t increment) const;

  // Appends a frame to one state transition result.
  template <typename Frame>
  void appendOutboundFrame(ProtocolStepResult* result, const Frame& frame) const {
    if (!result) {
      return;
    }
    CHTTP2_LOG_DEBUG("protocol: emit %s stream=%u len=%u",
                     frameTypeString(frame.header.type).c_str(),
                     frame.header.streamId,
                     frame.header.payloadLength);
    result->outbound.push_back(frame.toBytes());
  }

  FrameCodec frameCodec;
  std::unordered_map<StreamId, std::unique_ptr<Stream>> streams;

  // SETTINGS parameters with their default values.

  // max concurrent streams allowed by the peer. 0 means no limit.
  std::uint32_t maxConcurrentStreams;

  // HPACK dynamic table size limit advertised by the peer.
  std::uint32_t encodeHeaderTableSize;
  std::uint32_t decodeHeaderTableSize;

  // max frame size accepted by the peer.
  std::uint32_t maxFrameSize;
  std::uint32_t localMaxFrameSize;
  // window size for new streams, updated by peer SETTINGS frame.
  std::uint32_t initialWindowSize;

  // max header list size accepted by the peer. 0 means no limit.
  std::uint32_t maxHeaderListSize;
  bool enablePush;

  StreamId nextStreamId;
  StreamId lastPeerStreamId;

  bool started;
  bool closed;
  bool sentConnectionPreface;
  bool sentLocalSettings;
  bool gotPeerSettings;
  bool sentGoaway;
  bool receivedGoaway;
  bool transportClosed;
  bool expectingContinuation;
  StreamId continuationStreamId;

  ErrorCode connectionErrorCode;
  std::string connectionDebugData;
  std::uint64_t pingCounter{0};
  InFlow connectionInflow;
  OutFlow connectionOutFlow;
  Hpack hpack;

  // Header-block accumulator for streams already removed from streams_.
  // RFC 9113 §4.3 requires every header block to be HPACK-decoded even if
  // the decoded headers are discarded, to keep dynamic table state in sync.
  ByteBuffer ghostHeaderBlock;
};

}  // namespace chttp2
